---
# defaults file for roles/docker

docker_packages:
  - apt-transport-https
  - ca-certificates
  - curl
  - software-properties-common
  - docker-ce
  - docker-ce-cli
  - containerd.io
  - python3-pip
  - python3-docker
  - docker-compose

docker_repo: "deb [arch=amd64] https://download.docker.com/linux/ubuntu bionic stable"
docker_gpg_key: "https://download.docker.com/linux/ubuntu/gpg"
docker_gpg_key_id: 0EBFCD88

