---
# tasks file for roles/tooling

- name: create traefik network
  docker_network:
    name: traefik_net
    driver: overlay
  when: inventory_hostname in groups['managers']

- name: Deploy Traefik
  docker_swarm_service:
    name: traefik
    image: "traefik:latest"
    args:
    - "--log.level=INFO"
    - "--api.dashboard=true"
    - "--entryPoints.http.address=:80"
    - "--entryPoints.https.address=:443"
    - "--providers.docker=true"
    - "--providers.swarm=true"
    - "--certificatesResolvers.myresolver.acme.email=leobouvard08@gmail.com"
    - "--certificatesResolvers.myresolver.acme.storage=/letsencrypt/acme.json"
    - "--certificatesResolvers.myresolver.acme.tlsChallenge=true"
    labels:
      traefik.enable: "true"
      traefik.docker.network: "traefik_net"
      traefik.http.routers.traefik-public-http.rule: "Host(`traefik.leeodev.me`)"
      traefik.http.routers.traefik-public-http.entrypoints: "http"
      traefik.http.routers.traefik-public-http.middlewares: "https-redirect"
      traefik.http.middlewares.https-redirect.redirectscheme.scheme: "https"
      traefik.http.routers.traefik-public-http.service: "api@internal"
      traefik.http.services.traefik-public.loadbalancer.server.port: "8080"
      traefik.http.routers.traefik-public-https.rule: "Host(`traefik.leeodev.me`)"
      traefik.http.routers.traefik-public-https.entrypoints: "https"
      traefik.http.routers.traefik-public-https.tls.certresolver: "myresolver"
    replicas: 1
    publish:
      - target_port: 8080
        published_port: 8080
        protocol: tcp
        mode: ingress
    mounts:
      - type: bind
        source: /var/run/docker.sock
        target: /var/run/docker.sock
  when: inventory_hostname in groups['managers'][0]

  
