---
# tasks file for roles/docker

- name: add gpg key
  apt_key:
    url: "{{ docker_gpg_key }}"
    id: "{{ docker_gpg_key_id }}"

- name: add docker repository
  apt_repository:
    repo: "{{ docker_repo }}"

- name: install docker and dependencies
  apt:
    name: "{{ docker_packages }}"
    state: latest
    update_cache: yes
    cache_valid_time: 3600
  with_items: "{{ docker_packages }}"

- name: start docker service
  service:
    name: docker
    state: started
    enabled: yes